# Generated by Django 4.0.6 on 2022-08-09 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='person_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='persons.person'),
            preserve_default=False,
        ),
    ]
