# Generated by Django 4.0.6 on 2022-08-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipes_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='publicated',
            field=models.BooleanField(default=False),
        ),
    ]
