# Generated by Django 4.1 on 2022-09-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipes_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.TextField(max_length=528),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.TextField(max_length=528),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='rendiment',
            field=models.CharField(max_length=25),
        ),
    ]
